name: getx_app
description: "A new Flutter project."

# Prevents publishing to pub.dev by accident
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning for your app
version: 1.0.0+1

# Dart SDK version constraint
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter dependencies
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.17.0
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  image_picker: ^0.8.7+3  # Updated to the latest version of image_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Uncomment and add asset paths as needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and add font configurations as needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
